blank_issues_enabled: true
contact_links:
  - name: Private vulnerability reporting
    url: https://github.com/sebayaki/BrainBIP/security/advisories
    about: Choose Report a vulnerability to report a security issue privately.
